b main.go:52
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/server.go:353
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/server.go:373
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/client.go:181
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/client.go:168
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/client.go:170
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/client.go:99
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:92
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:98
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:108
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:116
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:117
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:120
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:139
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:140
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:205
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:221
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:242
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:246
b /home/xsuii/Studio/go/src/github.com/xsuii/dontsettle/servergo/xserver/file_manager.go:249